#!/usr/bin/env perl

use strict;
use warnings;

use Test::More 'tests' => 4;

use X11::GUITest qw(SendKeys SetInputFocus StartApp
                    WaitSeconds WaitWindowClose WaitWindowViewable);

{
    my $test = 'run program';

    StartApp('./uitest');
    my ($uitest) = WaitWindowViewable('ui-test');
    ok($uitest, "$test: found window");

    #system('xwd -name ui-test -out uitest.xwd');

    my $status = SetInputFocus($uitest);
    ok($status, "$test: set input focus");

    WaitSeconds(0.5);
    $status = SendKeys('{ESC}');
    ok($status, "$test: escape key sent");

    $status = WaitWindowClose($uitest);
    ok($status, "$test: window is gone");
}
