#!/usr/bin/env perl

use strict;
use warnings;

use Test::More 'tests' => 44;

use X11::GUITest qw(:ALL :CONST);

my $uitest;
my $screenshot_count = 0;

sub take_screenshot
{
    system("xwd -name ui-test -out uitest${screenshot_count}.xwd");
    ++$screenshot_count;
}

sub run_program
{
    my $test = 'run program';

    StartApp('./uitest');
    ($uitest) = WaitWindowViewable('ui-test');
    ok($uitest, "$test: found window");
}

sub interact_with_button
{
    my ($loc_x, $loc_y) = @_;
    my $test = 'button';

    my ($x, $y) = GetWindowPos($uitest);
    ok(defined $x, "$test: x pos is defined");
    ok(defined $y, "$test: y pos is defined");
    my $status = MoveMouseAbs($x + $loc_x, $y + $loc_y);
    ok($status, "$test: moved mouse to right spot");
    $status = PressMouseButton(M_BTN1);
    ok($status, "$test: pressed button 1");
    $status = MoveMouseAbs($x + $loc_x + 40, $y + $loc_y);
    ok($status, "$test: moved mouse again");
    $status = ReleaseMouseButton(M_BTN1);
    ok($status, "$test: released button 1");
    $status = ClickWindow($uitest, $loc_x, $loc_y, M_BTN2);
    ok($status, "$test: clicked button 2");
}

sub interact_with_row_column
{
    my $test = 'row-column';

    my $status = ClickWindow($uitest, 521, 36, M_BTN1);
    ok($status, "$test: reoriented row-column 1");

    $status = ClickWindow($uitest, 521, 36, M_BTN1);
    ok($status, "$test: re-reoriented row-column 1");

    $status = ClickWindow($uitest, 535, 50, M_BTN1);
    ok($status, "$test: printed out widget into");
}

sub interact_with_text_field
{
    my $test = 'text field';

    my ($x, $y) = GetWindowPos($uitest);
    ok(defined $x, "$test: x pos is defined");
    ok(defined $y, "$test: y pos is defined");
    my $status = MoveMouseAbs($x + 265, $y + 140);
    ok($status, "$test: moved mouse to text field");
    $status = SendKeys('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ');
    ok($status, "$test: lots of text");
    $status = SendKeys('{LEF}' x 62);
    ok($status, "$test: lots of left arrows");
    $status = SendKeys('{RIG}' x 62);
    ok($status, "$test: lots of right arrows");
    $status = SendKeys('{HOM}');
    ok($status, "$test: home key");
    $status = SendKeys('{END}');
    ok($status, "$test: end key");
    $status = SendKeys('{LEF}' x 20 . '{BAC}' x 30 . '{DEL}' x 5);
    ok($status, "$test: deleted stuff in the middle");
    $status = SendKeys('{LEF}' x 20);
    ok($status, "$test: beginning of string");
    $status = SendKeys('some more text');
    ok($status, "$test: inserted text at beginning");
}

sub interact_with_pie_menu
{
    my $test = 'pie menu';

    my ($x, $y) = GetWindowPos($uitest);
    ok(defined $x, "$test: x pos is defined");
    ok(defined $y, "$test: y pos is defined");
    my $status = MoveMouseAbs($x + 350, $y + 300);
    ok($status, "$test: moved mouse to right spot");
    $status = PressMouseButton(M_BTN1);
    ok($status, "$test: popped up pie menu");
    $status = MoveMouseAbs($x + 375, $y + 335);
    ok($status, "$test: moved into sector 0");
    $status = ReleaseMouseButton(M_BTN1);
    ok($status, "$test: popped down pie menu");

    $status = MoveMouseAbs($x + 350, $y + 300);
    ok($status, "$test: moved mouse to right spot again");
    $status = PressMouseButton(M_BTN1);
    ok($status, "$test: popped up pie menu");
    $status = MoveMouseAbs($x + 375, $y + 335);
    ok($status, "$test: moved into sector 0");
    $status = MoveMouseAbs($x + 375, $y + 285);
    ok($status, "$test: moved into sector 6");
    $status = ReleaseMouseButton(M_BTN1);
    ok($status, "$test: popped down pie menu");

    $status = MoveMouseAbs($x + 350, $y + 300);
    ok($status, "$test: moved mouse to right spot yet again");
    $status = PressMouseButton(M_BTN1);
    ok($status, "$test: popped up pie menu");
    $status = MoveMouseAbs($x + 350, $y + 299);
    ok($status, "$test: moved inside pie menu");
    $status = ReleaseMouseButton(M_BTN1);
    ok($status, "$test: popped down pie menu");

    $status = MoveMouseAbs($x + 350, $y + 300);
    ok($status, "$test: moved mouse to right spot once more");
    $status = PressMouseButton(M_BTN1);
    ok($status, "$test: popped up pie menu");
    $status = MoveMouseAbs($x + 251, $y + 240);
    ok($status, "$test: moved outside pie menu");
    $status = ReleaseMouseButton(M_BTN1);
    ok($status, "$test: popped down pie menu");
}

sub close_window
{
    my $test = 'close';

    my ($x, $y, $width, $height, $borderWidth) = GetWindowPos($uitest);
    my $status = MoveMouseAbs($x + $borderWidth + 1, $y + $borderWidth + 1);
    ok($status, "$test: moved mouse to upper left");

    $status = SendKeys('{ESC}');
    ok($status, "$test: escape key sent");

    $status = WaitWindowClose($uitest);
    ok($status, "$test: window is gone");
}

run_program();
BAIL_OUT("no window created, can't test anything else") if !$uitest;
interact_with_button(60, 185);
interact_with_row_column();
interact_with_text_field();
interact_with_pie_menu();
close_window();
