#!/usr/bin/env perl

use strict;
use warnings;

use Cwd qw/abs_path/;
use File::Basename;

use Test::More 'tests' => 6;

my $dir = dirname(dirname(abs_path(__FILE__))) . '/shaders';
while (my $file = glob("${dir}/*fragment*.glsl"))
{
    is(system(('glslangValidator', '-S', 'frag', $file)),
       0,
       'fragment shader ' . basename($file) . ' is OK');
}
while (my $file = glob("${dir}/*vertex*.glsl"))
{
    is(system(('glslangValidator', '-S', 'vert', $file)),
       0,
       'vertex shader ' . basename($file) . ' is OK');
}
